
openai-service:
  api-key: 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
  gpt-model: gpt-3.5-turbo
  audio-model: whisper-1
  http-client:
    read-timeout: 3000
    connect-timeout: 3000
  urls:
    base-url: https://api.openai.com/v1
    chat-url: /chat/completions
    create-transcription-url: /audio/transcriptions

server.port: 9027